name       : cf-cli
version    : 6.29.0
release    : 6
source     :
    - git|https://github.com/cloudfoundry/cli.git : v6.29.0
license    : Apache-2.0
component  : network.util
networking : yes
summary    : The official command line client for Cloud Foundry
description: |
    The official command line client for Cloud Foundry
builddeps  :
    - git
    - golang
setup      : |
    mkdir -p src/code.cloudfoundry.org/cli
    find $workdir/* -maxdepth 0 ! -name "src" -exec mv -v {} src/code.cloudfoundry.org/cli/ \;
build      : |
    export GOPATH=$workdir
    export PATH=$PATH:$GOPATH/bin
    cd $workdir/src/code.cloudfoundry.org/cli/
    bin/bootstrap
    bin/build
install    : |
    install -Dm000755 src/code.cloudfoundry.org/cli/out/cf $installdir/usr/bin/cf
