name       : cf-cli
version    : 6.23.0
release    : 2
source     :
    - https://github.com/cloudfoundry/cli/archive/v6.23.0.tar.gz : 73e8402fd24d93f0533fd4222ef0d749a2d3132a8da12a034357a846240ab2ee
license    : Apache-2.0
component  : network.util
extract    : no
networking : yes
summary    : The official command line client for Cloud Foundry
description: |
    The official command line client for Cloud Foundry
builddeps  :
    - git
    - golang
build      : |
    export GOPATH=$workdir
    export PATH=$PATH:$GOPATH/bin
    mkdir -p {bin,pkg,src}
    mkdir -p src/code.cloudfoundry.org/
    cd src/code.cloudfoundry.org/
    tar xf $sources/v$version.tar.gz
    mv cli-$version cli
    cd cli
    git init
    bin/build
install    : |
    install -Dm000755 src/code.cloudfoundry.org/cli/out/cf $installdir/usr/bin/cf
