name       : cf-cli
version    : 6.22.2
release    : 1
source     :
    - https://github.com/cloudfoundry/cli/archive/v6.22.2.tar.gz : fa5254a6e7197d9de86f3f9e1084d1f51f04cfa201b27c85b467a3320dbecda6
license    : Apache-2.0
component  : network.util
extract    : no
summary    : The official command line client for Cloud Foundry
description: |
    The official command line client for Cloud Foundry
builddeps  :
    - git
    - golang
build      : |
    export GOPATH=$workdir
    export PATH=$PATH:$GOPATH/bin
    mkdir -p {bin,pkg,src}
    mkdir -p src/code.cloudfoundry.org/
    cd src/code.cloudfoundry.org/
    tar xf $sources/v$version.tar.gz
    mv cli-$version cli
    cd cli
    git init
    bin/build
install    : |
    install -Dm000755 src/code.cloudfoundry.org/cli/out/cf $installdir/usr/bin/cf
